# Project configuration
general:
  inferBuildTool: true
  productiveBranch: 'main'

# Stage configuration
stages:
  'Confirm':
    manualConfirmation: false

#  npmAudit:
#    auditedAdvisories:

#  lint:
#    ui5BestPractices:
#      failThreshold:
#        error: <THRESHOLD>
#        warning: <THRESHOLD>
#        info: <THRESHOLD>

# deploy to Cloud Foundry
  productionDeployment:
    cfTargets:
      - appName: 'saasapp643'
        org: 'f0f82fb2trial'
        space: 'dev'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        credentialsId: 'deploy-to-cf'

# Step configuration
steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:
    versioningType: cloud_noTag

# transport management upload
#  tmsUpload:
#    nodeName: 'dev'
#    credentialsId: 'tms-sk'
#    customDescription: 'saasapp643 dev'
